import { CramDeck } from './cram-types';

export const SAMPLE_CRAM_DECKS: CramDeck[] = [
  {
    id: 'deck-csc301',
    title: 'Algorithms & Dynamic Programming',
    courseCode: 'CSC 301',
    description: 'High-yield algorithmic paradigms, recurrence relations, and graph shortcuts for midterm cramming.',
    cardCount: 5,
    estimatedMinutes: 6,
    category: 'Computer Science',
    cards: [
      {
        id: 'csc301-c1',
        course: 'CSC 301',
        topic: 'DYNAMIC PROGRAMMING',
        difficulty: 'High Yield',
        concept: 'Memoization vs Tabulation',
        recallPrompt: 'How do top-down and bottom-up DP differ in call overhead, state space computation, and subproblem ordering?',
        mnemonic: {
          hook: 'T-B, M-T (Table = Bottom-up, Memory = Top-down)',
          explanation: 'Tabulation builds from Base cases Upward into an array table; Memoization caches recursive calls from Target Top-down.',
        },
        plainIntuition: 'Memoization is remembering answers as you happen to bump into them recursively; Tabulation is assembling the answer row-by-row from ground zero.',
        breakdown: [
          '• Memoization: Combines recursion with cached hash map / array. Only evaluates needed subproblems on demand.',
          '• Tabulation: Purely iterative. Solves all subproblems in topological dependency order without recursion overhead.',
          '• Complexity: Both convert exponential O(2ⁿ) search trees into polynomial O(N · K) states.',
        ],
        examTrap: 'Memoization risks stack overflow on deep inputs due to recursion depth O(N). If stack space is limited, Tabulation is strictly required.',
        formulaOrCode: '// Top-down memo: dp[n] = solve(n-1) + solve(n-2)\n// Bottom-up tab:  dp[i] = dp[i-1] + dp[i-2]',
      },
      {
        id: 'csc301-c2',
        course: 'CSC 301',
        topic: 'ASYMPTOTIC ANALYSIS',
        difficulty: 'Exam Must-Know',
        concept: 'Master Theorem Shortcut',
        recallPrompt: 'Given recurrence T(n) = aT(n/b) + f(n), how do you compare leaf work n^(log_b a) with root work f(n)?',
        mnemonic: {
          hook: 'L-B-R (Leaves dominate, Balance, Root dominates)',
          explanation: 'Case 1 = Leaves win Θ(n^{log_b a}). Case 2 = Tie Θ(n^{log_b a} log n). Case 3 = Root wins Θ(f(n)).',
        },
        plainIntuition: 'The Master Theorem is a tug-of-war between the subproblem split cost at the bottom vs combining work done at the top.',
        breakdown: [
          '• Step 1: Compute watershed exponent c_crit = log_b(a).',
          '• If f(n) = O(n^{c_crit - ε}) (polynomial smaller): T(n) = Θ(n^{c_crit}).',
          '• If f(n) = Θ(n^{c_crit} · logᵏ n): T(n) = Θ(n^{c_crit} · log^{k+1} n).',
          '• If f(n) = Ω(n^{c_crit + ε}) and regularity holds: T(n) = Θ(f(n)).',
        ],
        examTrap: 'Master Theorem fails if f(n) differs from n^{c_crit} by a non-polynomial factor (e.g., 2ⁿ or n / log n). Use recurrence trees instead.',
        formulaOrCode: 'T(n) = aT(n/b) + O(nᵈ) => If d < log_b(a) => O(n^{log_b a})',
      },
      {
        id: 'csc301-c3',
        course: 'CSC 301',
        topic: 'GRAPH ALGORITHMS',
        difficulty: 'Crucial Formula',
        concept: 'Dijkstra vs Bellman-Ford vs Floyd-Warshall',
        recallPrompt: 'Which shortest-path algorithm handles negative edge weights, and which finds all-pairs shortest paths in O(V³)?',
        mnemonic: {
          hook: 'D-B-F: Direct (Positive), Bad (Neg edges), Full (All pairs)',
          explanation: 'Dijkstra for non-negative greedy search. Bellman-Ford for negative weights & cycle detection. Floyd-Warshall for dense all-pairs matrix.',
        },
        plainIntuition: 'Dijkstra is greedy and never looks back; Bellman-Ford checks every edge |V|-1 times to catch sneaky negative shortcuts.',
        breakdown: [
          '• Dijkstra: Single-source, weights ≥ 0. Runtime O((V + E) log V) with min-heap.',
          '• Bellman-Ford: Single-source, handles negative weights. Runtime O(V · E). Detects negative cycles on V-th relaxation.',
          '• Floyd-Warshall: All-pairs shortest path via 3 nested loops (k, i, j). Runtime O(V³), Space O(V²).',
        ],
        examTrap: 'Dijkstra produces incorrect paths on negative edges because the greedy premise (settled vertices cannot improve) breaks.',
      },
      {
        id: 'csc301-c4',
        course: 'CSC 301',
        topic: 'DATA STRUCTURES',
        difficulty: 'High Yield',
        concept: 'Amortized Analysis (Accounting & Potential)',
        recallPrompt: 'Why is dynamic array push O(1) amortized even though resizing costs O(N)?',
        mnemonic: {
          hook: 'Bank Deposit Analogy (Pay $3, Spend $1, Save $2)',
          explanation: 'Charge 3 credits per insert: 1 credit pays for current write, 1 moves this item during resize, 1 moves an older partner.',
        },
        plainIntuition: 'Amortization is averaging: the expensive resizing cost happens so rarely that the cheap $O(1)$ operations easily pay for it over time.',
        breakdown: [
          '• Aggregate Method: Total cost of k operations divided by k: T(k)/k.',
          '• Banker / Accounting Method: Charge extra credits on cheap ops to create a savings cushion for rare heavy ops.',
          '• Physicist / Potential Method: Define potential function Φ(state); amortized cost = actual cost + ΔΦ.',
        ],
        examTrap: 'Geometric doubling (2x) yields O(1) amortized. Arithmetic expansion (+100 slots) degrades amortized append to terrible O(N)!',
      },
      {
        id: 'csc301-c5',
        course: 'CSC 301',
        topic: 'COMPLEXITY THEORY',
        difficulty: 'Exam Must-Know',
        concept: 'P vs NP vs NP-Complete vs NP-Hard',
        recallPrompt: 'What is the exact distinction between NP (verifiable) and NP-Complete (hardest in NP)?',
        mnemonic: {
          hook: 'P = Play (Easy to solve), NP = Proof (Easy to verify)',
          explanation: 'P is solvable in polynomial time; NP is verifiable in polynomial time given a certificate/witness.',
        },
        plainIntuition: 'Solving a giant Sudoku is hard (NP), but once someone fills it in, checking if their answer is right takes seconds (P-verification).',
        breakdown: [
          '• P: Solvable deterministically in O(nᵏ).',
          '• NP: Solvable in poly-time on a non-deterministic machine; certifiable deterministically in poly-time.',
          '• NP-Hard: At least as hard as the hardest problems in NP (not necessarily in NP itself).',
          '• NP-Complete: Both in NP AND NP-Hard (e.g., SAT, 3-SAT, Traveling Salesperson, Vertex Cover).',
        ],
        examTrap: 'To prove a problem X is NP-Complete: first prove X ∈ NP, then reduce a KNOWN NP-Complete problem Y to X (Y ≤ₚ X), NOT X to Y!',
      },
    ],
  },
  {
    id: 'deck-sen301',
    title: 'Software Design & Architecture',
    courseCode: 'SEN 301',
    description: 'SOLID patterns, architectural trade-offs, and microservices heuristics for system design exams.',
    cardCount: 4,
    estimatedMinutes: 5,
    category: 'Software Engineering',
    cards: [
      {
        id: 'sen301-c1',
        course: 'SEN 301',
        topic: 'OBJECT-ORIENTED DESIGN',
        difficulty: 'Exam Must-Know',
        concept: 'The SOLID Principles',
        recallPrompt: 'What does each letter in SOLID represent, and what is the rule for Liskov Substitution?',
        mnemonic: {
          hook: 'S-O-L-I-D (Single, Open, Liskov, Interface, Dependency)',
          explanation: 'Single responsibility, Open/Closed (open for extension, closed for modification), Liskov substitution, Interface segregation, Dependency inversion.',
        },
        plainIntuition: 'SOLID is code hygiene: keep classes focused, make them pluggable without rewriting existing code, and depend on contracts, not concrete classes.',
        breakdown: [
          '• S: One class, one single reason to change.',
          '• O: Extend behavior via polymorphism without modifying audited source.',
          '• L: Subtypes must be substitutable for base types without breaking caller expectations.',
          '• I: Clients should not be forced to depend on methods they do not use.',
          '• D: High-level modules should depend on abstractions, never on low-level concretions.',
        ],
        examTrap: 'A classic Liskov violation is `Square extends Rectangle`. Changing `setWidth` on Square silently changes height, breaking rectangular invariants.',
      },
      {
        id: 'sen301-c2',
        course: 'SEN 301',
        topic: 'DATABASE SYSTEMS',
        difficulty: 'High Yield',
        concept: 'ACID vs BASE Guarantees',
        recallPrompt: 'How does transactional consistency in RDBMS (ACID) contrast with distributed eventual consistency (BASE)?',
        mnemonic: {
          hook: 'ACID = Bank Vault, BASE = Social Media Feed',
          explanation: 'ACID guarantees zero compromise on precision; BASE accepts temporary stale data for high availability and partition resilience.',
        },
        plainIntuition: 'ACID locks the register until the math balances; BASE says "I will post your photo now and sync the likes across servers over the next 2 seconds".',
        breakdown: [
          '• ACID: Atomicity (all-or-nothing), Consistency (rules preserved), Isolation (uninterrupted transactions), Durability (persisted to disk).',
          '• BASE: Basically Available, Soft-state (state can change without input), Eventual consistency (nodes converge).',
          '• CAP Theorem tie-in: CP systems favor ACID consistency; AP systems adopt BASE eventual consistency.',
        ],
        examTrap: 'Isolation levels trade correctness for performance. "Read Committed" prevents dirty reads but permits non-repeatable reads; only "Serializable" guarantees strict serial order.',
      },
      {
        id: 'sen301-c3',
        course: 'SEN 301',
        topic: 'DISTRIBUTED SYSTEMS',
        difficulty: 'Crucial Formula',
        concept: 'The CAP Theorem Trade-off',
        recallPrompt: 'Why is it mathematically impossible in a networked system to simultaneously achieve Consistency, Availability, and Partition Tolerance?',
        mnemonic: {
          hook: 'Pick Any Two, but P is Mandatory (CAP -> CP or AP)',
          explanation: 'Network partitions (cables cut, packet drop) are inevitable in real networks. Therefore, when P happens, you must choose C or A.',
        },
        plainIntuition: 'If your two data centers lose phone connection (Partition), you must either stop accepting updates (sacrifice Availability) or accept split updates (sacrifice Consistency).',
        breakdown: [
          '• Consistency (C): Every read receives the latest write or an error.',
          '• Availability (A): Every non-failing node returns a non-error response, without guarantee it is the latest.',
          '• Partition Tolerance (P): System continues operating despite arbitrary packet loss or node detachment.',
        ],
        examTrap: 'CA (Consistency + Availability without Partition tolerance) is impossible in distributed systems; it only exists on a single-node database without network splits.',
      },
      {
        id: 'sen301-c4',
        course: 'SEN 301',
        topic: 'DESIGN PATTERNS',
        difficulty: 'High Yield',
        concept: 'Observer vs Pub/Sub Pattern',
        recallPrompt: 'What is the critical architectural difference between the Gang of Four Observer and a Message Broker Pub/Sub?',
        mnemonic: {
          hook: 'Observer is a Direct Phone Call; Pub/Sub is a Post Office Bulletin',
          explanation: 'Observer subjects know their observers directly in-memory; Pub/Sub has an intermediate Event Channel / Message Broker completely decoupling them.',
        },
        plainIntuition: 'In Observer, the teacher yells directly to the students in the room; in Pub/Sub, the author tweets to anyone following the hashtag.',
        breakdown: [
          '• Observer: Synchronous in-memory subject keeps an array of observer listeners. Subject knows observer interfaces.',
          '• Pub/Sub: Publishers and Subscribers have zero awareness of each other. Messages route through brokers (Kafka, RabbitMQ, Redis).',
          '• Scalability: Pub/Sub scales horizontally across multiple servers and services; Observer lives within a single application process.',
        ],
        examTrap: 'Memory leaks in Observer patterns ("Lapsed Listener problem") happen when observers fail to unsubscribe, preventing garbage collection.',
      },
    ],
  },
];
